stages:
  prepare_data:
    cmd: python3 prepare.py
    deps:
    - dataset/creditors.csv
    - prepare.py
    outs:
    - dataset/creditors_ready.csv

  train:
    cmd: python3 train.py
    deps:
    - dataset/creditors_ready.csv
    - train.py
    params:
    - train.epochs
    - train.batch_size
    - model.units1
    - model.optimizer

    outs:
    - weights/best_loss.h5
    - weights/best_val_loss.h5
    metrics:
    - metrics/results.json:
        cache: false
    plots:
    - metrics/metrics.json:
        cache: false